export const CATALOG = [
    {
      key: "invoice-portal",
      title: "Lookalike invoice click",
      rule: "corr.phish.lookalike_portal",
      source: "mail-gw",
      host: "laptop-04",
      sev: 2,
      chain: ["lure", "harvest"],
      rems: ["reset", "quarantine"],
      disp: "contain",
      stream: [
        { t: "02:14:02", src: "mail-gw", sev: "med", rule: "Lookalike sender", msg: "from=invoices@acme-billing-secure.top reply-to≠from user=j.chen" },
        { t: "02:14:11", src: "proxy", sev: "med", rule: "First-seen domain", msg: "GET acme-billing-secure[.]top/login src=10.4.12.88 host=laptop-04 age=1d" },
        { t: "02:14:25", src: "idp", sev: "high", rule: "Password POST after click", msg: "user=j.chen app=legacy-sso src=10.4.12.88" },
        { t: "02:14:26", src: "edr", sev: "info", rule: "No new process", msg: "host=laptop-04 parent=none" },
        { t: "02:14:40", src: "siem", sev: "high", rule: "Correlation window", msg: "mail click → rare domain → password POST  3/3 matched" },
      ],
      teach: {
        chain: "Order: deliver the lookalike lure, then harvest the password. No payload ran on the laptop.",
        cut: "Reset the harvested account and quarantine the lure mail. Isolating a clean laptop does nothing.",
        disp: "Disposition: true positive — Tier-1 can contain by resetting the harvested account.",
      },
    },
    {
      key: "rundll-temp",
      title: "rundll32 from Temp",
      rule: "corr.malware.office_rundll",
      source: "edr",
      host: "pos-12",
      sev: 3,
      chain: ["lure", "execute", "c2"],
      rems: ["isolate", "block_hash"],
      disp: "escalate",
      stream: [
        { t: "03:41:08", src: "mail-gw", sev: "low", rule: "Macro-enabled attachment", msg: "name=Q3-invoice.docm user=pos-12$" },
        { t: "03:41:19", src: "edr", sev: "high", rule: "Office spawned rundll32", msg: "WINWORD → eqnedt32 → rundll32 host=pos-12 path=C:\\Users\\Public\\Temp\\a.dll" },
        { t: "03:41:22", src: "edr", sev: "high", rule: "AMSI bypass string", msg: "module=a.dll unsigned=true" },
        { t: "03:42:20", src: "proxy", sev: "high", rule: "Periodic beacon", msg: "dst=185.203.44.19:443 ja3=unknown interval=60s host=pos-12" },
        { t: "03:42:21", src: "siem", sev: "crit", rule: "Correlation window", msg: "macro → rundll → C2  host still on LAN" },
      ],
      teach: {
        chain: "Order: lure (macro doc) → execute (rundll32) → C2 beacon. Host is the patient.",
        cut: "Isolate the host and block the dropped file hash so the fleet is covered.",
        disp: "Disposition: escalate to IR after isolating — active payload and C2 need incident response.",
      },
    },
    {
      key: "vpn-spray",
      title: "VPN spray then success",
      rule: "corr.intrusion.vpn_spray",
      source: "vpn",
      host: "vpn-edge",
      sev: 2,
      chain: ["brute", "access"],
      rems: ["block_ip"],
      disp: "contain",
      stream: [
        { t: "04:02:01", src: "vpn", sev: "med", rule: "Failed logon burst", msg: "src=91.224.22.18 asn=AS198605 user=svc-backup count=40" },
        { t: "04:02:08", src: "vpn", sev: "med", rule: "Same /24 probe", msg: "src=91.224.22.18 users=svc-backup,svc-scan,svc-wds" },
        { t: "04:02:11", src: "vpn", sev: "high", rule: "Success after spray", msg: "user=svc-backup src=91.224.22.18 mfa=none (legacy)" },
        { t: "04:02:12", src: "idp", sev: "info", rule: "No travel ticket", msg: "user=svc-backup geo=none-of-offices first-seen=now" },
        { t: "04:02:13", src: "siem", sev: "high", rule: "Correlation window", msg: "spray → success  src still connected" },
      ],
      teach: {
        chain: "Order: brute/spray the VPN, then access on success. No lure, no file.",
        cut: "The same address is still the door. Block it at the edge.",
        disp: "Disposition: true positive — block the source and close as contained.",
      },
    },
    {
      key: "gift-cards",
      title: "Urgent wire from 'CEO'",
      rule: "corr.phish.bec_giftcards",
      source: "helpdesk",
      host: "hr-pc",
      sev: 1,
      chain: ["lure"],
      rems: ["quarantine", "purge"],
      disp: "contain",
      stream: [
        { t: "09:11:04", src: "helpdesk", sev: "low", rule: "User report", msg: "“CEO needs $8k in cards, don’t call”  queue=finance" },
        { t: "09:11:06", src: "mail-gw", sev: "med", rule: "Display-name spoof", msg: "display=A. Rowe envelope=ceo-office@acme-holdlngs.co" },
        { t: "09:11:10", src: "mail-gw", sev: "med", rule: "Same lure fan-out", msg: "recipients=14 window=6m clicks=0 auth=0" },
        { t: "09:11:12", src: "idp", sev: "info", rule: "No password POST", msg: "finance group: no new auths" },
        { t: "09:11:13", src: "siem", sev: "med", rule: "Correlation window", msg: "BEC lure still sitting in inboxes" },
      ],
      teach: {
        chain: "Order stops at lure. Nobody clicked and nobody typed a password — the mail is still the weapon.",
        cut: "Quarantine the lure and purge lookalike copies still in mailboxes.",
        disp: "Disposition: true positive — quarantine the lure and close.",
      },
    },
    {
      key: "psexec-share",
      title: "PsExec onto the share",
      rule: "corr.intrusion.psexec_lateral",
      source: "siem",
      host: "jump-box",
      sev: 3,
      chain: ["access", "move"],
      rems: ["isolate"],
      disp: "escalate",
      stream: [
        { t: "11:08:01", src: "siem", sev: "med", rule: "SMB enum", msg: "src=jump-box dst=10.4.12.0/24 port=445" },
        { t: "11:08:14", src: "siem", sev: "high", rule: "Service install", msg: "host=FS-02 name=PSEXESVC parent=jump-box$ user=SYSTEM" },
        { t: "11:08:15", src: "edr", sev: "high", rule: "PsExec artifact", msg: "host=jump-box file=psexec.exe interactive=true" },
        { t: "11:08:16", src: "backup", sev: "info", rule: "No encrypt", msg: "host=FS-02 vss=ok note=none" },
        { t: "11:08:17", src: "siem", sev: "crit", rule: "Correlation window", msg: "enum → PsExec  pivot still interactive" },
      ],
      teach: {
        chain: "Order: foothold already has access, then lateral move with PsExec. Not encrypt, not a lure.",
        cut: "The live pivot is jump-box. Isolate that host.",
        disp: "Disposition: escalate to IR — lateral movement is an active intrusion.",
      },
    },
    {
      key: "mfa-blast",
      title: "MFA reset blast",
      rule: "corr.phish.mfa_kit",
      source: "mail-gw",
      host: "mail-gw",
      sev: 1,
      chain: ["lure"],
      rems: ["block_domain"],
      disp: "contain",
      stream: [
        { t: "07:55:00", src: "mail-gw", sev: "med", rule: "Bulk MFA lure", msg: "count=200 subject=reset your MFA unique-links=true" },
        { t: "07:55:04", src: "dns", sev: "high", rule: "New lookalike domain", msg: "qname=login-okta-acme.xyz age=11h" },
        { t: "07:55:10", src: "proxy", sev: "low", rule: "Low click rate", msg: "clicks=3 password_POST=0" },
        { t: "07:55:11", src: "ti", sev: "med", rule: "Infra overlap", msg: "same sending AS as last month credential kit" },
        { t: "07:55:12", src: "siem", sev: "med", rule: "Correlation window", msg: "mass lure + staged kit, harvest not started" },
      ],
      teach: {
        chain: "Order stops at lure. The kit is staged but harvest has not started.",
        cut: "Kill the landing site so remaining clicks go nowhere.",
        disp: "Disposition: true positive — block the kit domain and close.",
      },
    },
    {
      key: "vssadmin",
      title: "Shadow copies gone",
      rule: "corr.ransom.vss_wipe",
      source: "backup",
      host: "fs-02",
      sev: 3,
      chain: ["encrypt"],
      rems: ["isolate"],
      disp: "escalate",
      stream: [
        { t: "01:02:10", src: "backup", sev: "high", rule: "Backup job failed", msg: "host=fs-02 job=nightly-legal" },
        { t: "01:02:11", src: "edr", sev: "crit", rule: "vssadmin delete shadows", msg: "host=fs-02 cmd=vssadmin delete shadows /all /quiet" },
        { t: "01:02:18", src: "siem", sev: "crit", rule: "Mass rename", msg: "share=\\\\fs-02\\legal ext=.locked count=8400" },
        { t: "01:02:19", src: "siem", sev: "high", rule: "Ransom note drop", msg: "file=HELP.txt shares=legal,finance,hr" },
        { t: "01:02:20", src: "siem", sev: "crit", rule: "Correlation window", msg: "vss kill + encrypt + note  admin SMB still open" },
      ],
      teach: {
        chain: "Order is impact: encrypt (shadow wipe + mass rename). Earlier stages already happened off-camera.",
        cut: "The host is still a spreader over admin SMB. Isolate it.",
        disp: "Disposition: escalate to IR — ransomware prep needs full response.",
      },
    },
    {
      key: "fwd-rule",
      title: "Quiet auto-forward",
      rule: "corr.phish.inbox_forward",
      source: "idp",
      host: "sso-01",
      sev: 2,
      chain: ["lure", "harvest", "persist"],
      rems: ["revoke", "remove_rule"],
      disp: "contain",
      stream: [
        { t: "02:14:03", src: "o365", sev: "high", rule: "New inbox rule", msg: "user=p.nguyen cond=subject:invoice dest=gmail.com src=coffee-shop-ASN" },
        { t: "02:14:03", src: "idp", sev: "med", rule: "OWA login", msg: "user=p.nguyen method=password+cookie host=none" },
        { t: "02:13:40", src: "proxy", sev: "med", rule: "Lookalike Okta (yesterday)", msg: "user=p.nguyen dst=okta-acme-sso[.]top" },
        { t: "02:14:10", src: "edr", sev: "info", rule: "Laptop clean", msg: "host=hr-pc malware=false" },
        { t: "02:14:11", src: "siem", sev: "high", rule: "Correlation window", msg: "lure → OWA → forward rule  tokens still valid" },
      ],
      teach: {
        chain: "Order: lure yesterday → harvest the session → persist with an inbox forward rule.",
        cut: "Revoke the mailbox sessions and remove the malicious inbox rule.",
        disp: "Disposition: true positive — revoke the mailbox session and close.",
      },
    },
    {
      key: "cobalt-named",
      title: "Named pipe on hr-pc",
      rule: "corr.malware.beacon_pipe",
      source: "edr",
      host: "hr-pc",
      sev: 3,
      chain: ["lure", "execute", "c2"],
      rems: ["isolate", "kill_proc"],
      disp: "escalate",
      stream: [
        { t: "10:22:01", src: "mail-gw", sev: "low", rule: "XLSM inbound", msg: "name=payroll-q3.xlsm user=p.nguyen" },
        { t: "10:22:18", src: "edr", sev: "high", rule: "Excel spawned rundll32", msg: "host=hr-pc parent=EXCEL.EXE pipe=msagent_*" },
        { t: "10:22:19", src: "edr", sev: "crit", rule: "Explorer injection", msg: "host=hr-pc tid=injected profile=beacon" },
        { t: "10:22:20", src: "ad", sev: "high", rule: "TGT still valid", msg: "host=hr-pc user=p.nguyen" },
        { t: "10:22:21", src: "siem", sev: "crit", rule: "Correlation window", msg: "xlsm → pipe → inject  host on LAN" },
      ],
      teach: {
        chain: "Order: lure (xlsm) → execute (rundll / inject) → C2 beacon profile.",
        cut: "Isolate the beacon host and kill the named-pipe process.",
        disp: "Disposition: escalate to IR — named-pipe beacon is confirmed C2.",
      },
    },
    {
      key: "sso-impossible",
      title: "Impossible travel on SSO",
      rule: "corr.intrusion.impossible_travel",
      source: "idp",
      host: "sso-01",
      sev: 2,
      chain: ["token", "consent"],
      rems: ["revoke", "revoke_cloud"],
      disp: "handoff",
      stream: [
        { t: "09:02:00", src: "idp", sev: "info", rule: "HQ sign-in", msg: "user=a.rowe geo=HQ method=hw-key" },
        { t: "09:11:04", src: "idp", sev: "high", rule: "Impossible travel", msg: "user=a.rowe geo=Lagos delta=9m method=password+cookie" },
        { t: "09:11:06", src: "idp", sev: "high", rule: "Refresh token minted", msg: "user=a.rowe app=PDF Preview unverified=true" },
        { t: "09:11:08", src: "edr", sev: "info", rule: "Laptop never left", msg: "host=a.rowe-lpt process=none" },
        { t: "09:11:09", src: "siem", sev: "high", rule: "Correlation window", msg: "cookie reuse + rogue consent  no host payload" },
      ],
      teach: {
        chain: "Order: steal the session/token, then abuse it to consent a rogue app. No file on the laptop.",
        cut: "Revoke IdP sessions and the cloud session — token theft spans both.",
        disp: "Disposition: hand off to Tier-2 identity — token theft needs deeper session review.",
      },
    },
    {
      key: "c2-dns",
      title: "DGA-looking DNS",
      rule: "corr.malware.dga_hit",
      source: "dns",
      host: "laptop-04",
      sev: 2,
      chain: ["c2"],
      rems: ["block_domain", "isolate"],
      disp: "escalate",
      stream: [
        { t: "13:40:00", src: "dns", sev: "med", rule: "NXDOMAIN storm", msg: "host=laptop-04 qtype=A count=40 pattern=5-letter.top" },
        { t: "13:40:11", src: "dns", sev: "high", rule: "DGA answered", msg: "qname=xqjrm.top a=172.93.44.9" },
        { t: "13:40:12", src: "ti", sev: "high", rule: "Sinkhole list hit", msg: "ip=172.93.44.9 list=last-week-c2" },
        { t: "13:40:13", src: "edr", sev: "info", rule: "Kiosk host", msg: "host=laptop-04 role=kiosk isolate=optional-if-c2-dies" },
        { t: "13:40:14", src: "siem", sev: "high", rule: "Correlation window", msg: "DGA + known C2  live lever is the name" },
      ],
      teach: {
        chain: "What you see is C2 calling home. Earlier stages are off-camera; the live lever is the lookup.",
        cut: "Block the C2 domain and isolate the talking host.",
        disp: "Disposition: escalate to IR after blocking — DNS C2 implies a foothold.",
      },
    },
    {
      key: "rdp-brute",
      title: "RDP hammer on jump-box",
      rule: "corr.intrusion.rdp_brute",
      source: "vpn",
      host: "jump-box",
      sev: 2,
      chain: ["brute", "access"],
      rems: ["block_ip"],
      disp: "contain",
      stream: [
        { t: "16:01:00", src: "fw", sev: "med", rule: "RDP failure storm", msg: "dst=jump-box:3389 src=45.134.1.88 count=2000 window=10m vpn=false" },
        { t: "16:01:11", src: "fw", sev: "high", rule: "RDP success", msg: "user=Administrator src=45.134.1.88" },
        { t: "16:01:12", src: "edr", sev: "info", rule: "No payload on disk", msg: "host=jump-box malware=false session=live" },
        { t: "16:01:13", src: "siem", sev: "high", rule: "Correlation window", msg: "exposed RDP brute → admin  src still in" },
      ],
      teach: {
        chain: "Order: brute the exposed RDP, then access as Administrator.",
        cut: "Close the door: block the source. No ransom yet.",
        disp: "Disposition: true positive — block the source IP and close.",
      },
    },
    {
      key: "macro-drop",
      title: "Macro dropped a payload",
      rule: "corr.malware.macro_drop",
      source: "edr",
      host: "laptop-04",
      sev: 2,
      chain: ["lure", "execute", "c2"],
      rems: ["isolate", "block_hash"],
      disp: "escalate",
      stream: [
        { t: "14:03:02", src: "mail-gw", sev: "low", rule: "Vendor-thread hijack", msg: "from=known-vendor.doc thread=hijacked user=j.chen" },
        { t: "14:03:20", src: "edr", sev: "high", rule: "WINWORD → powershell -enc", msg: "host=laptop-04" },
        { t: "14:03:22", src: "edr", sev: "crit", rule: "Payload written", msg: "path=%AppData%\\update.exe sha256=9f3a…c21 unsigned=true running=true" },
        { t: "14:03:24", src: "edr", sev: "med", rule: "Cached SAP creds", msg: "host=laptop-04 role=finance" },
        { t: "14:03:25", src: "siem", sev: "crit", rule: "Correlation window", msg: "macro → enc ps → live hash" },
      ],
      teach: {
        chain: "Order: lure (hijacked thread) → execute (encoded powershell / drop) → C2 from the binary.",
        cut: "Isolate the patient and block the payload hash.",
        disp: "Disposition: escalate to IR after isolate — malware drop needs hunt and cleanup.",
      },
    },
    {
      key: "bitlocker-note",
      title: "Wallpaper changed on DC",
      rule: "corr.ransom.dc_impact",
      source: "siem",
      host: "dc-01",
      sev: 3,
      chain: ["encrypt"],
      rems: ["isolate"],
      disp: "escalate",
      stream: [
        { t: "01:44:01", src: "edr", sev: "crit", rule: "Recovery disabled", msg: "host=dc-01 bcdedit=recovery-off vss=stopped" },
        { t: "01:44:08", src: "edr", sev: "crit", rule: "cipher /w", msg: "host=dc-01 volume=D: status=paused" },
        { t: "01:44:09", src: "siem", sev: "high", rule: "Wallpaper ransom note", msg: "host=dc-01" },
        { t: "01:44:10", src: "ad", sev: "crit", rule: "Only DC in site", msg: "host=dc-01 sysvol=writable-from-self" },
        { t: "01:44:11", src: "siem", sev: "crit", rule: "Correlation window", msg: "impact on DC  isolate before SYSVOL push" },
      ],
      teach: {
        chain: "Order is impact: encrypt on the DC (recovery killed + wipe + note).",
        cut: "Isolate before this box pushes the rest of the site via SYSVOL.",
        disp: "Disposition: escalate to IR immediately — ransomware on a DC.",
      },
    },
    {
      key: "oauth-spam",
      title: "Consent prompt flood",
      rule: "corr.phish.oauth_consent",
      source: "idp",
      host: "sso-01",
      sev: 1,
      chain: ["lure", "consent"],
      rems: ["revoke_oauth"],
      disp: "contain",
      stream: [
        { t: "08:20:01", src: "helpdesk", sev: "low", rule: "User report", msg: "“review document” asked to accept an app  n=several" },
        { t: "08:20:04", src: "idp", sev: "high", rule: "Unverified app", msg: "app=Contoso Docs created=today scopes=Mail.Read,Files.Read.All,offline_access" },
        { t: "08:20:06", src: "idp", sev: "high", rule: "Consent granted", msg: "users=3 refresh_tokens=issued" },
        { t: "08:20:07", src: "edr", sev: "info", rule: "No host malware", msg: "laptops=clean" },
        { t: "08:20:08", src: "siem", sev: "high", rule: "Correlation window", msg: "consent lure  tokens already minted" },
      ],
      teach: {
        chain: "Order: lure the user into the consent prompt, then consent grants the rogue app.",
        cut: "Tokens are minted. Revoke the sessions / app. Isolating laptops misses the token.",
        disp: "Disposition: true positive — revoke the OAuth grant and close.",
      },
    },
    {
      key: "exfil-share",
      title: "Odd night copy off FS-02",
      rule: "corr.exfil.share_staging",
      source: "siem",
      host: "wifi-ap",
      sev: 2,
      chain: ["access", "exfil"],
      rems: ["isolate", "block_ip"],
      disp: "escalate",
      stream: [
        { t: "23:10:02", src: "siem", sev: "high", rule: "After-hours share read", msg: "src=wifi-ap share=\\\\FS-02\\legal bytes=18GB user=asleep" },
        { t: "23:12:40", src: "edr", sev: "high", rule: "7z staging", msg: "host=wifi-ap path=%TEMP%\\legal.7z" },
        { t: "23:14:01", src: "proxy", sev: "crit", rule: "MEGA upload", msg: "dst=mega.nz progress=40% ssid=guest" },
        { t: "23:14:02", src: "siem", sev: "crit", rule: "Correlation window", msg: "pack → personal cloud  box is the leak" },
      ],
      teach: {
        chain: "Order: access on the workstation, then exfil to personal cloud. Not a phish, not encrypt.",
        cut: "Isolate the exfil host and block the destination IP.",
        disp: "Disposition: escalate to IR — data theft is an incident, not a Tier-1 close.",
      },
    },
    {
      key: "kerberoast-svc",
      title: "Kerberoast on svc-sql",
      rule: "corr.intrusion.kerberoast",
      source: "siem",
      host: "dc-01",
      sev: 2,
      chain: ["harvest", "access"],
      rems: ["disable", "reset"],
      disp: "handoff",
      stream: [
        { t: "18:02:01", src: "ad", sev: "med", rule: "TGS-REQ spike", msg: "src=hr-pc spn=MSSQLSvc/db-01.acme.local count=1" },
        { t: "18:02:20", src: "ad", sev: "high", rule: "RC4 ticket request", msg: "user=svc-sql enc=rc4-hmac" },
        { t: "18:18:03", src: "idp", sev: "high", rule: "svc-sql used from new host", msg: "src=jump-box first-seen=true" },
        { t: "18:18:04", src: "edr", sev: "info", rule: "No malware on hr-pc", msg: "host=hr-pc" },
        { t: "18:18:05", src: "siem", sev: "high", rule: "Correlation window", msg: "roast → cracked svc login  disable the service account" },
      ],
      teach: {
        chain: "Order: harvest the service ticket hash, then access as the cracked service account.",
        cut: "Disable the roasted service account and reset its credentials.",
        disp: "Disposition: hand off to Tier-2 identity — disable the service account and escalate the roast.",
      },
    },
  {
      key: "noise-vendor-update",
      title: "Signed updater from Temp",
      rule: "corr.noise.signed_updater",
      source: "edr",
      host: "eng-22",
      sev: 1,
      noise: true,
      chain: [],
      rems: ["no_action"],
      disp: "fp",
      stream: [
        { t: "10:02:01", src: "edr", sev: "med", rule: "Process from Temp", msg: "host=eng-22 path=C:\\Users\\Public\\Temp\\Setup.exe" },
        { t: "10:02:02", src: "edr", sev: "info", rule: "Authenticode valid", msg: "publisher=Contoso Imaging Ltd thumbprint=known-good" },
        { t: "10:02:04", src: "proxy", sev: "low", rule: "Vendor CDN", msg: "dst=cdn.contoso-imaging.com category=software-update" },
        { t: "10:02:05", src: "change", sev: "info", rule: "Change ticket", msg: "CHG4412 · scanner firmware push · owner=IT-Ops" },
        { t: "10:02:06", src: "siem", sev: "med", rule: "Correlation window", msg: "Temp path + network — but signed + ticketed update" },
      ],
      teach: {
        chain: "No attacker chain. This is a signed, ticketed vendor updater that happened to run from Temp.",
        cut: "Do not isolate. Close with no containment — optionally ask detections to tune Temp+signed noise.",
        disp: "Disposition: false positive — expected change activity.",
      },
    },
    {
      key: "noise-pentest",
      title: "External scan burst",
      rule: "corr.noise.pentest_scan",
      source: "siem",
      host: "edge-fw",
      sev: 2,
      noise: true,
      chain: [],
      rems: ["no_action"],
      disp: "benign",
      stream: [
        { t: "13:40:00", src: "fw", sev: "high", rule: "Port scan", msg: "src=203.0.113.44 ports=22,80,443,3389,445 rate=high" },
        { t: "13:40:30", src: "vpn", sev: "med", rule: "Auth failures", msg: "src=203.0.113.44 users=admin,root,test count=12" },
        { t: "13:41:00", src: "ti", sev: "info", rule: "Allowlist hit", msg: "src in pentest-range · vendor=RedTeam Co · window=13:00-17:00" },
        { t: "13:41:02", src: "mail-gw", sev: "info", rule: "Engagement notice", msg: "subject=External pentest today · from=security@" },
        { t: "13:41:03", src: "siem", sev: "med", rule: "Correlation window", msg: "scan + fails — matches approved pentest window" },
      ],
      teach: {
        chain: "No attacker chain. Traffic matches today’s approved external pentest.",
        cut: "No block/isolate. Close as benign / expected.",
        disp: "Disposition: benign — authorized testing.",
      },
    },
    {
      key: "noise-mailer",
      title: "Bulk mail lookalike",
      rule: "corr.noise.marketing_mailer",
      source: "mail-gw",
      host: "mx-01",
      sev: 1,
      noise: true,
      chain: [],
      rems: ["tune_rule"],
      disp: "fp",
      stream: [
        { t: "09:05:01", src: "mail-gw", sev: "med", rule: "Lookalike brand", msg: "display=Acme Benefits from=notify@acme-hr-updates.com" },
        { t: "09:05:02", src: "mail-gw", sev: "low", rule: "High volume", msg: "recipients=420 template=open-enrollment" },
        { t: "09:05:04", src: "dns", sev: "info", rule: "Domain age", msg: "acme-hr-updates.com age=4y spf=pass dkim=pass" },
        { t: "09:05:05", src: "helpdesk", sev: "info", rule: "Campaign notice", msg: "HR open-enrollment mailer scheduled this week" },
        { t: "09:05:06", src: "siem", sev: "med", rule: "Correlation window", msg: "lookalike display — auth passes + HR ticket" },
      ],
      teach: {
        chain: "No lure chain. HR’s real mailer trips lookalike heuristics.",
        cut: "Don’t quarantine org-wide. Request a detection tune; no containment.",
        disp: "Disposition: false positive — tune the rule.",
      },
    },
    {
      key: "noise-backup",
      title: "Mass rename on share",
      rule: "corr.noise.backup_rotate",
      source: "backup",
      host: "fs-archive",
      sev: 2,
      noise: true,
      chain: [],
      rems: ["no_action"],
      disp: "benign",
      stream: [
        { t: "02:10:00", src: "siem", sev: "high", rule: "Mass rename", msg: "share=\\\\fs-archive\\nightly count=12000 ext=.bak" },
        { t: "02:10:01", src: "backup", sev: "info", rule: "Job running", msg: "job=rotate-legal-archive status=success" },
        { t: "02:10:02", src: "edr", sev: "info", rule: "Known backup agent", msg: "host=fs-archive process=BackupAgent.exe signed=true" },
        { t: "02:10:03", src: "siem", sev: "low", rule: "No ransom note", msg: "HELP.txt=false vss=intact" },
        { t: "02:10:04", src: "siem", sev: "med", rule: "Correlation window", msg: "rename spike — matches nightly rotate" },
      ],
      teach: {
        chain: "No encrypt chain. Nightly archive rotation renames files by design.",
        cut: "Do not isolate the archive host. Close as benign.",
        disp: "Disposition: benign — expected backup behavior.",
      },
    },
    {
      key: "noise-sso-lab",
      title: "Lab password POST burst",
      rule: "corr.noise.sso_lab",
      source: "idp",
      host: "lab-sso",
      sev: 1,
      noise: true,
      chain: [],
      rems: ["no_action"],
      disp: "fp",
      stream: [
        { t: "15:22:01", src: "idp", sev: "med", rule: "Password POST burst", msg: "app=lab-sso user=qa-* count=30" },
        { t: "15:22:02", src: "proxy", sev: "low", rule: "Lab VLAN only", msg: "src=10.90.0.0/16 dst=lab-sso.acme.local" },
        { t: "15:22:03", src: "idp", sev: "info", rule: "Test tenants", msg: "env=nonprod mfa=disabled-by-policy" },
        { t: "15:22:04", src: "change", sev: "info", rule: "QA script", msg: "AUT-882 · login soak test · owner=IAM-QA" },
        { t: "15:22:05", src: "siem", sev: "med", rule: "Correlation window", msg: "burst auths — scoped to lab + ticket" },
      ],
      teach: {
        chain: "No harvest. QA soak test against non-prod SSO.",
        cut: "No resets or disables on lab identities. Close FP.",
        disp: "Disposition: false positive — lab traffic.",
      },
    },
];

